[package]
name = "bitcoin"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"
rand = "0.9.2"
reqwest = { version = "0.13.1", features = ["blocking"] }
sha2 = "0.10"
thiserror = "2.0.17"
